//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeOff.UI.Proxies.StaffService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.StaffService.IStaffService")]
    public interface IStaffService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/Add", ReplyAction="http://tempuri.org/IStaffService/AddResponse")]
        string Add(TimeOff.ComponentModel.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/Update", ReplyAction="http://tempuri.org/IStaffService/UpdateResponse")]
        void Update(TimeOff.ComponentModel.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/Delete", ReplyAction="http://tempuri.org/IStaffService/DeleteResponse")]
        void Delete(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/Get", ReplyAction="http://tempuri.org/IStaffService/GetResponse")]
        TimeOff.ComponentModel.User Get(string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaffServiceChannel : TimeOff.UI.Proxies.StaffService.IStaffService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffServiceClient : System.ServiceModel.ClientBase<TimeOff.UI.Proxies.StaffService.IStaffService>, TimeOff.UI.Proxies.StaffService.IStaffService {
        
        public StaffServiceClient() {
        }
        
        public StaffServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public string Add(TimeOff.ComponentModel.User user)
        {
            return base.Channel.Add(user);
        }

        public void Update(TimeOff.ComponentModel.User user)
        {
            base.Channel.Update(user);
        }
        
        public void Delete(string userId) {
            base.Channel.Delete(userId);
        }

        public TimeOff.ComponentModel.User Get(string userId)
        {
            return base.Channel.Get(userId);
        }
    }
}
