//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeOff.UI.Proxies.VacationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.VacationService.IVacationService")]
    public interface IVacationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/SubmitRequest", ReplyAction="http://tempuri.org/IVacationService/SubmitRequestResponse")]
        string SubmitRequest(string userId, System.DateTime[] days);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/CancelRequest", ReplyAction="http://tempuri.org/IVacationService/CancelRequestResponse")]
        void CancelRequest(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/ApproveRequest", ReplyAction="http://tempuri.org/IVacationService/ApproveRequestResponse")]
        void ApproveRequest(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/RejectRequest", ReplyAction="http://tempuri.org/IVacationService/RejectRequestResponse")]
        void RejectRequest(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/GetAvailableDaysByUser", ReplyAction="http://tempuri.org/IVacationService/GetAvailableDaysByUserResponse")]
        TimeOff.ComponentModel.Days GetAvailableDaysByUser(string userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVacationService/GetAvailableDaysByAllUsers", ReplyAction="http://tempuri.org/IVacationService/GetAvailableDaysByAllUsersResponse")]
        TimeOff.ComponentModel.UserDays[] GetAvailableDaysByAllUsers();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVacationServiceChannel : TimeOff.UI.Proxies.VacationService.IVacationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VacationServiceClient : System.ServiceModel.ClientBase<TimeOff.UI.Proxies.VacationService.IVacationService>, TimeOff.UI.Proxies.VacationService.IVacationService {
        
        public VacationServiceClient() {
        }
        
        public VacationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VacationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SubmitRequest(string userId, System.DateTime[] days) {
            return base.Channel.SubmitRequest(userId, days);
        }
        
        public void CancelRequest(string requestId) {
            base.Channel.CancelRequest(requestId);
        }
        
        public void ApproveRequest(string requestId) {
            base.Channel.ApproveRequest(requestId);
        }
        
        public void RejectRequest(string requestId) {
            base.Channel.RejectRequest(requestId);
        }

        public TimeOff.ComponentModel.Days GetAvailableDaysByUser(string userid)
        {
            return base.Channel.GetAvailableDaysByUser(userid);
        }

        public TimeOff.ComponentModel.UserDays[] GetAvailableDaysByAllUsers()
        {
            return base.Channel.GetAvailableDaysByAllUsers();
        }
    }
}
